### ISSUE TITLE
Does not work when App is killed (iOS 15.0)

### ISSUE THREAD

**Issue by chrizstone** [Dev-hwang/geofence_service#11]
Sadly, it does not work when the app is completely terminated. I builded the app exactly like you did in your example. Any tips or reasons why this is not working?

**Comment by Dev-hwang** [comment]
@chrizstone 

This plugin will not work when the app is completely terminated. As explained in the `readme`, this plugin only works while the app is alive. If you want full background geofencing, try another plugin.
