### ISSUE TITLE
WillStartForegroundTask blocks WillPopScope

### ISSUE THREAD

**Issue by kamami** [Dev-hwang/geofence_service#13]
The `onWillPop` method of WillPopScope is ignored when the child is WillStartForegroundTask.
Also reordering the widget tree does not help. When removing WillStartForegroundTask from the widget, WillPopScope  is working as expected.

```
WillPopScope(
        onWillPop: () async {
          print("POP"); 
          Navigator.of(context).maybePop();
          return false;
        },
          child: 
               WillStartForegroundTask(
                onWillStart: () async {
                 ...
```

**Comment by Dev-hwang** [comment]
The `WillStartForegroundTask` widget in this plugin is already using the `WillPopScope` widget. If you use more than one `WillPopScope` widget in one widget, I know that only the `WillPopScope` widget directly above the `Scaffold` will work.

Therefore, it is recommended to copy the `WillStartForegroundTask` widget code and customize it.
