### ISSUE TITLE
Updating the data on iOS

### ISSUE THREAD

**Issue by niclasGru** [Dev-hwang/geofence_service#14]
In Android (according to the default settings in the interval of 5000 milliseconds), the data is output to the console after the specified time. On iOS, however, this only happens once when the app is opened and then no longer. Is this a bug with the iOS simulator or is this normal? I always run it via Xcode (for Android via Visual Studio Code). Thanks !

**Comment by Dev-hwang** [comment]
It seems to be an iOS simulator bug. Try testing with a real device.
