### ISSUE TITLE
Not working when app is removed

### ISSUE THREAD

**Issue by iamfarmankhan** [Dev-hwang/geofence_service#15]
When app is minimised and in foreground everything work fine but when app is closed location update and geofence both not working. 

Getting below error - 

Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.pravera.com/fl_location/updates. Response ID: 0

**Comment by Dev-hwang** [comment]
If the app is completely closed by the process manager, this plugin will not work. This plugin does not yet support background processing.

The above error occurs because the app is completely closed, but the method channel for communicating with the native code is not closed properly. Check if the `stopWithTask` value of the Android service tag is set to `true`.

```xml
<service
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="location"
    android:stopWithTask="true" />
```

**Comment by Dev-hwang** [comment]
This plugin has not yet implemented background processing. As explained in the readme, this plugin only works while the app is alive.

**Comment by Dev-hwang** [comment]
The above error occurs when the method channel for communicating with native code is not properly closed.

Try this method!

1. Set the `android:stopWithTask` option to `true`.

2. Add the following line to your `pubspec.yaml` file.
```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

3. Run the following command.
```
flutter clean
flutter pub get
```

4. Set `isSticky` value to `false` in AndroidNotificationOptions settings.

Added process exit code to clear communication channel and memory when service is abnormally terminated.

**Comment by iamfarmankhan** [comment]
Thanks a lot @Dev-hwang for quick response. This solved that error message. But it'll be great if this plugin works in when app is closed also. Thanks again for this great plugin.

**Comment by Dev-hwang** [comment]
Thank you. If there is a chance, I will implement background processing as well.
