### ISSUE TITLE
Unable to kill app from Paused state in Android

### ISSUE THREAD

**Issue by stantonius** [Dev-hwang/geofence_service#16]
Firstly, thank you for your (continued) work on this and other libraries.

When the Android app is running in the foreground (in a Paused lifecycle state), and when I kill the app by swiping it up from the App Overview (the third button in a 3-button navigation layout), the emulator does not exit and I get the following recurring message:

```
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. 
Could not send. Channel: plugins.pravera.com/fl_location/updates. Response ID: 12
```
Note this behaviour doesn't happen if you kill the app by selecting the App Overview button when the app is Active - only when the app is already in the foreground and paused (I have a habit of closing the apps on my phone periodically, and I noticed the battery usage of this app spiked following killing of the app)

I have tried setting `android:stopWithTask="false"` and calling dispose manually, and many different attempts to cancel the stream listener manually - however it seems killing the app running in foreground kills the Flutter engine before cancelling the location calculation stream and I don't know how to reorder this sequence. The Android Studio Logcat error that I also tried to unsuccessfully troubleshoot is below:

```
2021-12-05 01:42:02.642 533-3929/system_process W/InputManager-JNI: Input channel object '32225f9 com.example.test_app2/com.example.test_app2.MainActivity (client)' was disposed without first being removed with the input manager!
2021-12-05 01:42:02.644 533-562/system_process W/UsageStatsService: Unexpected activity event reported! (com.example.test_app2/com.example.test_app2.MainActivity event : 23 instanceId : 209389694)
```

I created a repo with the current setup embedded in a basic Flutter app here: https://github.com/stantonius/geolocation_debug_app

Any ideas about why this might be occurring?  

The flutter doctor is below

```
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0-3.3.pre at /Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (3 days ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Library/Android/sdk
    • Java binary at: /Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at 
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.55
```

**Comment by Dev-hwang** [comment]
The above error occurs when the method channel for communicating with native code is not properly closed. I will check the problem.

**Comment by Dev-hwang** [comment]
1. Set the `android:stopWithTask` option to `true`.

2. Add the following line to your `pubspec.yaml` file.
```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

3. Run the following command.
```
flutter clean
flutter pub get
```

4. Set `isSticky` value to `false` in AndroidNotificationOptions settings.

Added process exit code to clear communication channel and memory when service is abnormally terminated.

**Comment by Dev-hwang** [comment]
The above error occurs when the method channel for communicating with native code is not properly closed.

Try this method!

1. Set the `android:stopWithTask` option to `true`.

2. Add the following line to your `pubspec.yaml` file.
```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

3. Run the following command.
```
flutter clean
flutter pub get
```

4. Set `isSticky` value to `false` in AndroidNotificationOptions settings.

Added process exit code to clear communication channel and memory when service is abnormally terminated.

**Comment by stantonius** [comment]
Brilliant. This worked. Many thanks for your work and quick responses.
