### ISSUE TITLE
Remove Notification

### ISSUE THREAD

**Issue by hrtzzz11** [Dev-hwang/geofence_service#18]
How to remove the notifications (from the method WillStartForegroundTask() ) for Android devices? For iOS I just set showNotification = false. But there is not (or I haven't found it yet) a similar approach for Android notifications. If I remove the notifications in the "WillStartForegroundTask" method (or set them to zero, i.e. androidNotificationOptions: null), the app crashes as soon as I leave it

**Comment by Dev-hwang** [comment]
A foreground service is required to track background location on the Android platform. The notification serves to notify the user that the foreground service has started.

So, if you want to remove the notification, you don't need to use the `WillStartForegroundTask` widget. However, it may not be able to track your location in the background.

**Comment by hrtzzz11** [comment]
Alright, understand. And what about those two notifications? The upper one is created with an other plugin. The one below is the one from WillStartForegroundTask() (see code below). Is this lower one even visible when the user got the app on a real device (because that's how I want it)?


home: WillStartForegroundTask(
          onWillStart: () async {
            // You can add a foreground task start condition.
            return _geofenceService.isRunningService;
          },
          androidNotificationOptions: const AndroidNotificationOptions(
            channelId: 'geofence_service_notification_channel',
            channelName: 'Geofence Service Notification',
            channelDescription:
                'This notification appears when the geofence service is running in the background.',
            channelImportance: NotificationChannelImportance.NONE,
            priority: NotificationPriority.MIN,
            isSticky: false,
            visibility: NotificationVisibility.VISIBILITY_SECRET,
            showWhen: false,
          ),
          iosNotificationOptions:
              const IOSNotificationOptions(showNotification: false),
          notificationTitle: 'xxx',
          notificationText: 'yyy',
          child: Scaffold(.........


<img width="330" alt="sc" src="https://user-images.githubusercontent.com/95595953/145009030-ebc3bf3e-89d6-4134-baad-b755a73417d3.png">

**Comment by Dev-hwang** [comment]
A notification must be created to start a foreground service. A foreground service is also called a service that is visible to the user. So, just because a channel is of low importance cannot hide a notification.

**Comment by Dev-hwang** [comment]
I don't speak English well, so I didn't understand what the question was. It would be helpful to answer if you could explain a little more.

**Comment by hrtzzz11** [comment]
Yes, no problem, thank you for taking your time :-)  

I don’t want the user to get notifications when the foreground task (method willStartForegroundTask)
() ) is called. Therefore, i set (for iOS) iosNotificationOptions:
const IOSNotificationOptions(showNotification: false) and now the notification of this method isn’t shown on iOS

For Android, i want to do the same but there isn’t a similar boolean like „showNotification“ and i can’t set androidNotificationOptions: null because then the app crashes. That’s why i set IMPORTANCE_NONE, but the notification is still there (see the picture, it it the lower notification with grey icon), and somehow you can’t delete this notification on the simulator.

So two questions: 
1) Is it possible to not show the Android notification (like the iOS notification with the boolean showNotification)?
2) Will the notification on a real device be shown, when it’s set IMPORTANCE_NONE?

**Comment by Dev-hwang** [comment]
1. No. The notification could not be removed. To start the foreground service according to the Android platform's policy, must create a notification.

2. For the same reason as above, the notification appears even if the notification importance is set to 'NONE' or 'LOW'. Also, users cannot remove notifications.

**Comment by hrtzzz11** [comment]
Aight thank u! :)
