### ISSUE TITLE
Multiple _geofenceServices

### ISSUE THREAD

**Issue by hrtzzz11** [Dev-hwang/geofence_service#19]
Is there a way to create multiple _geofenceServices and run them both? I want to have two geofence-Services with a different loiteringDelayMs. Thanks!

**Comment by Dev-hwang** [comment]
This plugin is implemented as a singleton pattern, so you cannot create two geofence services. Also, you cannot have different loiteringDelayMs. Unfortunately, it seems better to use other plugins.
