### ISSUE TITLE
Optional Activity Stream

### ISSUE THREAD

**Issue by phcs971** [Dev-hwang/geofence_service#2]
I removed the activity permissions and the setOnActivityChanged once I don't have a real use for those data. But when I call the service the app crashes and returns `"[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data."`. Is there a way to prevent this? Thank you

By the way, I am currently on version 1.0.3 because this app is still in flutter 1.22.6

**Comment by Dev-hwang** [comment]
Currently, this plugin is a geofence service with activity recognition, so the activity recognition permission is required. However, some users may need to provide an option because activity recognition may not be required. We will update the options today.

**Comment by Dev-hwang** [comment]
> I removed the activity permissions and the setOnActivityChanged once I don't have a real use for those data. But when I call the service the app crashes and returns `"[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data."`. Is there a way to prevent this? Thank you
> 
> By the way, I am currently on version 1.0.3 because this app is still in flutter 1.22.6

Plugin updated! To disable the activity recognition API, set the useActivityRecognition option to false.

```dart
final geofenceService = GeofenceService(
  interval: 2500,
  accuracy: 100,
  useActivityRecognition: false,
  allowMockLocations: false
);
```

And recommend to upgrade the Flutter version.

**Comment by phcs971** [comment]
Thank you
