### ISSUE TITLE
send text between devices

### ISSUE THREAD

**Issue by staminna** [Dev-hwang/geofence_service#20]
Dear Dev-hwang,

Is it possible to send text messages between users within the geofence?

**Comment by Dev-hwang** [comment]
The question is difficult to understand. I would appreciate it if you could explain in more detail.

**Comment by staminna** [comment]
In case there are two or more people in the geofence with geo_fence running, is it possible to text between "nearby" users?

**Comment by Dev-hwang** [comment]
This plugin does not support communication between devices.

**Comment by Dev-hwang** [comment]
Try implementing that functionality using a plugin that supports [mqtt](https://pub.dev/packages/mqtt_client). When entering the geofence area, you can implement it by connecting to the mqtt server.
