### ISSUE TITLE
 unable to get any notification

### ISSUE THREAD

**Issue by SanaShokat** [Dev-hwang/geofence_service#21]
I am using this package in my project. I  have added all dependencies mentioned in the Read.me  but there is no notification shown on my mobile when geofence trigger .Dev logs shows the status change of geofence but no notification is visible. Can anyone help me with this

**Comment by Dev-hwang** [comment]
Notification generated by this plugin do not appear when the geofence service is started or triggered. A notification appears when the geofence service is started and the app enters the background.

The reason the notification is created is to start a foreground service. On the Android platform, apps need certain permissions and foreground services to navigate to a background location without going to sleep. For more information, see [here](https://developer.android.com/guide/components/foreground-services) / [here](https://developer.android.com/training/location/background).
