### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient,

### ISSUE THREAD

**Issue by maulanauls** [Dev-hwang/geofence_service#25]
Hi, can you check whats this problem on this case 
I got forced closed app then i have error this like this 

`java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/com.kiatanandagroup.driver-UsfQeG2gVgt3Cq3AzhaG7Q==/base.apk)
E/AndroidRuntime(12461): 	at com.pravera.fl_location.service.LocationDataProvider.checkLocationSettingsAndStartLocationUpdates(LocationDataProvider.kt:68)
E/AndroidRuntime(12461): 	at com.pravera.fl_location.service.LocationDataProvider.requestLocationUpdates(LocationDataProvider.kt:60)
E/AndroidRuntime(12461): 	at com.pravera.fl_location.service.LocationDataProviderManager.requestLocationUpdates(LocationDataProviderManager.kt:47)
E/AndroidRuntime(12461): 	at com.pravera.fl_location.LocationStreamHandlerImpl.onListen(LocationStreamHandlerImpl.kt:39)
E/AndroidRuntime(12461): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/AndroidRuntime(12461): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/AndroidRuntime(12461): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(12461): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(12461): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime(12461): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(12461): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(12461): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(12461): 	at android.app.ActivityThread.main(ActivityThread.java:8034)
E/AndroidRuntime(12461): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12461): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
I/Process (12461): Sending signal. PID: 12461 SIG: 9`

**Comment by michaeljajou** [comment]
I am also facing this same issue

**Comment by aminovicnouri** [comment]
any updates?

**Comment by JuanJoseR** [comment]
Hi, any new updates? I am also facing the same issue

**Comment by JuanJoseR** [comment]
Hi, i solved this issue by doing two things:
- removing the `location` dependency from my project and instead using `geolocator`
- adding the following lines in `build.gradle`:
```
allprojects {
    repositories {   
        google()
        mavenCentral()
        //This lines
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:21.0.1"
            }
        }
    }
}

```

Hope it helps!
