### ISSUE TITLE
ForegroundService Exception

### ISSUE THREAD

**Issue by kamami** [Dev-hwang/geofence_service#3]
When clicking on a notification triggered by `onGeofenceStatusChanged`, I get following error:

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{845dc41 u0 com.example.xxx/com.pravera.geofence_service.foreground_service.ForegroundSer
vice}
```
I implemented the plugin according to your guide and also changed the AndroidManifest.xml.
The notification is accomplished with the `flutter_local_notifications` package, but the error seems to be within this package.

**Comment by Dev-hwang** [comment]
> When clicking on a notification triggered by `onGeofenceStatusChanged`, I get following error:
> 
> ```
> android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{845dc41 u0 com.example.xxx/com.pravera.geofence_service.foreground_service.ForegroundSer
> vice}
> ```
> 
> I implemented the plugin according to your guide and also changed the AndroidManifest.xml.
> The notification is accomplished with the `flutter_local_notifications` package, but the error seems to be within this package.

The above problem is expected to be one of the two below.

1. After Oreo (SDK 26), When calling Context.startForegroundService(), it must be connected to the notification with startForeground() of the Service instance within 5 seconds, but if the connection is delayed

2. When stopService() is called before switching to the foreground state (before the foreground variable of the running Service instance becomes true) and restarts with Context.startForegroundService()

Problem 2 has been fixed. Could you please update the plugin to check it out?

**Comment by kamami** [comment]
Thank you for your blazing support!
I tested it for some minutes and it seems to work so far.
I will test it more this afternoon!
