### ISSUE TITLE
Geofence is not working on background state

### ISSUE THREAD

**Issue by kodega2016** [Dev-hwang/geofence_service#32]
location is not being used while app is in background, but when we use the **flutter_foreground_task** from the master branch directly it is working

**Comment by HYEOKCHOENCHOI** [comment]
> location is not being used while app is in background, but when we use the **flutter_foreground_task** from the master branch directly it is working

Is this issue closed? When the app is closed(not terminated) In API10L, the background location trace is working. But in API12L is NOT...
