### ISSUE TITLE
I want to run Geofence_Service in the background

### ISSUE THREAD

**Issue by keisuketsumurai** [Dev-hwang/geofence_service#33]
안녕하세요, 
Geofence service를 백그라운드에서 실행하는 방법에 대해 문의 드립니다.
현재, 어플을 종료하면 geofence service도 종료되어버리는 상황입니다. 이를 아래와 같이 해결하고 싶은데 방법을 잘 몰라서 문의드립니다.
	1	geofence service를 5분 간격으로 백그라운드에서 실행시키고 싶습니다.
	2	geofence 반경 안에 유저가 들어갈 경우 local notification이 오게 하고 싶습니다. (어플 실행 중이 아닐 때도 local notification이 오도록 하고 싶습니다.)
위 두가지 사항이 geofence 패키지에서 가능한지, 또한 가능하다면 그 방법에 대해 알려주시면 감사하겠습니다.
바쁘신 와중에 문의 드려 죄송합니다.
감사합니다.

I am having trouble getting Geofence_Service to stop when I kill the app.
The two functions we would like to achieve are.
1.I would like to run Geofence_Service in the background at 5 minute intervals.
2.I would like to send out a local notification when a Geofence is crossed.

**Comment by kyadalu1** [comment]
try this https://www.youtube.com/watch?v=Z_wBnBjHb6U

**Comment by Musyimi97** [comment]
> try this https://www.youtube.com/watch?v=Z_wBnBjHb6U

This youtube video you provided is set to premier in 83 days?
