### ISSUE TITLE
When the background service will be added

### ISSUE THREAD

**Issue by suraj740** [Dev-hwang/geofence_service#6]
Hi @Dev-hwang , I am using this plugin and  its really nice, but when the app is in  background its not listening.
I want the app to listen in background as well.
Any help would be appreciated!!
Thanks !!

**Comment by Dev-hwang** [comment]
@suraj740 

1. Check that the permissions and services are properly declared as shown below.

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

<service
    android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
    android:foregroundServiceType="location"
    android:stopWithTask="true" />
```

2. Please use the `WillStartForegroundTask` widget.

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    // A widget used when you want to start a foreground task when trying to minimize or close the app.
    // Declare on top of the [Scaffold] widget.
    home: WillStartForegroundTask(
      onWillStart: () {
        // You can add a foreground task start condition.
        return _geofenceService.isRunningService;
      },
      notificationOptions: NotificationOptions(
        channelId: 'geofence_service_notification_channel',
        channelName: 'Geofence Service Notification',
        channelDescription: 'This notification appears when the geofence service is running in the background.',
        channelImportance: NotificationChannelImportance.LOW,
        priority: NotificationPriority.LOW,
      ),
      notificationTitle: 'Geofence Service is running',
      notificationText: 'Tap to return to the app',
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Geofence Service'),
          centerTitle: true,
        ),
        body: _buildContentView(),
      ),
    ),
  );
}
```

3. Make sure the location permission is always allowed. Please check the android [homepage](https://developer.android.com/training/location/permissions#request-background-location) for details.

![image](https://user-images.githubusercontent.com/47127353/125624385-293849bc-62f3-42ad-a27c-d5d1f65285b7.png)

**NOTE**: Currently uploaded plug-in can only perform geofencing while the app is alive. You can use the `WillStartForegroundTask` widget to prevent the app from closing when the back or home button is pressed, but the service is unavailable if the app is forcibly killed by the system. In the future, I plan to implement a service so that it can run in the background even when the app is closed.

**Comment by suraj740** [comment]
Thanks @Dev-hwang for responding, I have used the same config as above. 
I am Getting geofence notifications when the app is open and WillStartForegroundTask notification when trying to close the app. 

 But when the app is closed or terminated i am not getting any geofence notification.

**Comment by Dev-hwang** [comment]
What platform is using this plug-in? If it is an Android platform, is the notification being shown properly when you start the geofence service?

You're saying that the app only works when it's foreground, right?

**Comment by suraj740** [comment]
@Dev-hwang I am using it in both android and iOS.

Yes the app only works when in foreground.

**Comment by Dev-hwang** [comment]
See this [project](https://github.com/Dev-hwang/geofence_sample). I tested it in the environment below and there was no problem.

* Flutter sdk.  2.2.3 / 2.5.2
* Android ver - 9(sim), 10(sim), 11(real)
* iOS ver - 10(sim), 11(sim), 12(sim), 13(real), 14(sim)

The service worked properly unless the app was forcibly closed. (Works in situations such as leaving the home screen, turning off the screen, or leaving the home screen by pressing the back button)

**Comment by suraj740** [comment]
Thanks @Dev-hwang , will try the above one once.

**Comment by suraj740** [comment]
Hi @Dev-hwang, i have tried your project got the same issue when app is not running or is closed.
Apps works only when it is running in background or in foreground.
But Not getting any updates when is closed(not running in background).

Tested in oneplus device.

**Comment by Dev-hwang** [comment]
As mentioned above, this plugin only works while the app is alive. This plugin does not work if you force exit the app through the process manager or press the back button without using the WillStartForegroundTask widget.

If you want a geofence service that runs completely in the background, i recommend using another plugin.

thanks
