### ISSUE TITLE
ForegroundTask is always on

### ISSUE THREAD

**Issue by kamami** [Dev-hwang/geofence_service#9]
I am asking the user for permission to track the location always or only while using the app via permission_handler package. I am storing this bool in a global variable. How can I prevent the ForegroundTask to start when the permission for the background is not given?
At the moment the pin in the statusbar disappears for 1 second when closing the app, but appears again immediately afterwards.

How can I prevent the app from using the location when being closed? 

![InkedWhatsApp Image 2021-11-12 at 18 13 35_LI](https://user-images.githubusercontent.com/43880037/141507738-34574ffc-fde5-4b10-ade1-bfb3257def33.jpg)

This is my code:

          `@override
               Widget build(BuildContext context) {
                   return WillStartForegroundTask(
                         onWillStart: () {
                             // You can add a foreground task start condition.

                               if (permissions.background.value) {
                                          print("ONWILLSTART");
                              
                                          return true;
                                        } else {
                                          print("ONWILLSTARTNOT");
                              
                                          return false;
                                        }
            },`

When closing the app it prints "ONWILLSTARTNOT", but the notification disappears and comes back immediately. 

Any idea what I am doing wrong?

**Comment by Dev-hwang** [comment]
@kamami 

Can you provide the git source like last time?

**Comment by kamami** [comment]
I tried the whole day to recreate the issue, but I did not manage to do so.
Maybe my undertsanding of this feature is wrong.
Could you explain, what exactly this "WillStartForegroundTask" manages? 
Is it repsonsible for my Google Maps to track my location in the background? Or is it only responsible for showing the according notification on my device?

**Comment by Dev-hwang** [comment]
The `WillStartForegroundTask` widget serves to help the app enter a background state without exiting when the user tries to close or minimize the app. The background state is when the user navigates from the app to the home screen or turns off the device's screen.

In fact, the `WillStartForegroundTask` widget has nothing to do with location tracking. It just starts a foreground service, which prevents the app from going into a [Doze](https://developer.android.com/training/monitoring-device-state/doze-standby) state and helps it track location in the background. This is a widget you don't need to use unless you're tracking location in the background.

Among the contents of `Readme`, the code below means the following:

If the user tries to close the app while `_geofenceService` is running, it starts the foreground service and puts the app in the background state.

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    home: WillStartForegroundTask(
      onWillStart: () {
        // You can add a foreground task start condition.
        return _geofenceService.isRunningService;
      },
      androidNotificationOptions: AndroidNotificationOptions(
        channelId: 'geofence_service_notification_channel',
        channelName: 'Geofence Service Notification',
        channelDescription: 'This notification appears when the geofence service is running in the background.',
        channelImportance: NotificationChannelImportance.LOW,
        priority: NotificationPriority.LOW,
        isSticky: false,
      ),
      iosNotificationOptions: IOSNotificationOptions(),
      notificationTitle: 'Geofence Service is running',
      notificationText: 'Tap to return to the app',
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Geofence Service'),
          centerTitle: true,
        ),
        body: _buildContentView(),
      ),
    ),
  );
}
```

**Comment by kamami** [comment]
Thank you, I understand now! Since I want to track the location of the user in the background, this is actually the exact behaviour I need. But I indeed observed, that the `_onGeofenceStatusChanged` method is called, even if the foreground service was not started, because of my permissions. Do I also need to have some conditions inside of this method? I thought it will automatically not be called, if the foreground service was not started.

**Comment by Dev-hwang** [comment]
The `WillStartForegroundTask` widget and `GeofenceService` are separate. Even if the foreground service is not started, `GeofenceService` will work if it has location permission.

**Comment by Dev-hwang** [comment]
It would be helpful to solve the problem if you easily explain what function you are trying to implement.

**Comment by kamami** [comment]
So the general idea is a map with many point of interest with geofences. The user gets a push notification if he enters one of those geofences. 

The first screen of the app shows 2 toggles to choose whether or not the app should also track and send out notifications while the app is sleeping. In this scenario the app should stop tracking and sending out notifications while the app is sleeping, because the user only allowed to be tracked while using the app. 

Permission handling is already working well! But the logic for the `geofence_service` when to stop and when to restart the service is giving me headache. 
I hope this makes my use case a little more clearer :)

**First screen to select the permission (start can only be clicked if at least one is selected)**
<img src="https://user-images.githubusercontent.com/43880037/142159265-d01f665f-2587-4ebc-9c17-458d4717e0ae.jpg" width="450" height="855">

**Second screen: Map with point of interests**
<img src="https://user-images.githubusercontent.com/43880037/142159301-1df24228-f4e0-4f8c-a4f1-ad64dbf93f1f.jpeg" width="450" height="855">

**Comment by Dev-hwang** [comment]
How about this way? `allowBackground` is the value set in the first screen. If the first screen allows background location tracking, it starts the foreground, otherwise it doesn't.

Even if Android has background location permission, location tracking cannot be done in the background unless the foreground service is running. Here's how to take advantage of this limitation.

```dart
  @override
  Widget build(BuildContext context) {
    Widget child = Scaffold(
      appBar: AppBar(
        title: const Text('Geofence Service'),
        centerTitle: true,
      ),
      body: Container(),
    );

    if (allowBackground) {
      child = WillStartForegroundTask(
        onWillStart: () async {
          // You can add a foreground task start condition.
          return _geofenceService.isRunningService;
        },
        androidNotificationOptions: const AndroidNotificationOptions(
          channelId: 'geofence_service_notification_channel',
          channelName: 'Geofence Service Notification',
          channelDescription: 'This notification appears when the geofence service is running in the background.',
          channelImportance: NotificationChannelImportance.LOW,
          priority: NotificationPriority.LOW,
          isSticky: false,
        ),
        iosNotificationOptions: const IOSNotificationOptions(),
        notificationTitle: 'Geofence Service is running',
        notificationText: 'Tap to return to the app',
        child: child,
      );
    }

    return MaterialApp(
      home: child,
    );
  }
```

**Comment by kamami** [comment]
Can be closed! Thanks for the help
